<?
require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetTitle("Новая страница");
?>
<section>
	<div class="container">
		<?$APPLICATION->IncludeComponent("bitrix:breadcrumb", "zp", Array(
			"START_FROM" => "0",	// Номер пункта, начиная с которого будет построена навигационная цепочка
			"PATH" => "",	// Путь, для которого будет построена навигационная цепочка (по умолчанию, текущий путь)
			"SITE_ID" => "s1",	// Cайт (устанавливается в случае многосайтовой версии, когда DOCUMENT_ROOT у сайтов разный)
		),
			false
		);?>
	</div>
</section>
<section>
	<div class="container">
		<h1 class="h2 mb-40">Программы питания</h1>
	</div>
</section>
<section class="section">
	<div class="container">
		<?$APPLICATION->IncludeComponent(
	"bitrix:news",
	"programs",
	array(
		"ADD_ELEMENT_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"AJAX_MODE" => "Y",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "Y",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "N",
		"CHECK_DATES" => "Y",
		"DETAIL_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "N",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => array(
			0 => "SHOW_COUNTER",
			1 => "",
		),
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "DAY1ZHORCAL",
			1 => "DAY1ZHORNAME",
			2 => "DAY1SECONDBREAKFASTCAL",
			3 => "DAY1BREAKFASTCAL",
			4 => "DAY1DINNERCAL",
			5 => "DAY1RATIONCAL",
			6 => "DAY1AFTERNONCAL",
			7 => "DAY1LUNCHCAL",
			8 => "DAY0ZHORCAL",
			9 => "DAY0ZHORNAME",
			10 => "DAY0SECONDBREAKFASTCAL",
			11 => "DAY0BREAKFASTCAL",
			12 => "DAY0DINNERCAL",
			13 => "DAY0RATIONCAL",
			14 => "DAY0AFTERNONCAL",
			15 => "DAY0LUNCHCAL",
			16 => "DAY2ZHORCAL",
			17 => "DAY2ZHORNAME",
			18 => "DAY2SECONDBREAKFASTCAL",
			19 => "DAY2BREAKFASTCAL",
			20 => "DAY2DINNERCAL",
			21 => "DAY2RATIONCAL",
			22 => "DAY2AFTERNONCAL",
			23 => "DAY2LUNCHCAL",
			24 => "DAY3ZHORCAL",
			25 => "DAY3ZHORNAME",
			26 => "DAY3SECONDBREAKFASTCAL",
			27 => "DAY3BREAKFASTCAL",
			28 => "DAY3DINNERCAL",
			29 => "DAY3RATIONCAL",
			30 => "DAY3AFTERNONCAL",
			31 => "DAY3LUNCHCAL",
			32 => "DAY4ZHORCAL",
			33 => "DAY4ZHORNAME",
			34 => "DAY4SECONDBREAKFASTCAL",
			35 => "DAY4BREAKFASTCAL",
			36 => "DAY4DINNERCAL",
			37 => "DAY4RATIONCAL",
			38 => "DAY4AFTERNONCAL",
			39 => "DAY4LUNCHCAL",
			40 => "DAY5ZHORCAL",
			41 => "DAY5ZHORNAME",
			42 => "DAY5SECONDBREAKFASTCAL",
			43 => "DAY5BREAKFASTCAL",
			44 => "DAY5DINNERCAL",
			45 => "DAY5RATIONCAL",
			46 => "DAY5AFTERNONCAL",
			47 => "DAY5LUNCHCAL",
			48 => "DAY6ZHORCAL",
			49 => "DAY6ZHORNAME",
			50 => "DAY6SECONDBREAKFASTCAL",
			51 => "DAY6BREAKFASTCAL",
			52 => "DAY6DINNERCAL",
			53 => "DAY6RATIONCAL",
			54 => "DAY6AFTERNONCAL",
			55 => "DAY6LUNCHCAL",
			56 => "DAY7ZHORCAL",
			57 => "DAY7ZHORNAME",
			58 => "DAY7SECONDBREAKFASTCAL",
			59 => "DAY7BREAKFASTCAL",
			60 => "DAY7DINNERCAL",
			61 => "DAY7RATIONCAL",
			62 => "DAY7AFTERNONCAL",
			63 => "DAY7LUNCHCAL",
			64 => "DAY8ZHORCAL",
			65 => "DAY8ZHORNAME",
			66 => "DAY8SECONDBREAKFASTCAL",
			67 => "DAY8BREAKFASTCAL",
			68 => "DAY8DINNERCAL",
			69 => "DAY8RATIONCAL",
			70 => "DAY8AFTERNONCAL",
			71 => "DAY8LUNCHCAL",
			72 => "DAY9ZHORCAL",
			73 => "DAY9ZHORNAME",
			74 => "DAY9SECONDBREAKFASTCAL",
			75 => "DAY9BREAKFASTCAL",
			76 => "DAY9DINNERCAL",
			77 => "DAY9RATIONCAL",
			78 => "DAY9AFTERNONCAL",
			79 => "DAY9LUNCHCAL",
			80 => "DAY8ZHOR",
			81 => "DAY8SECONDBREAKFAST",
			82 => "DAY8BREAKFAST",
			83 => "DAY8DINNER",
			84 => "DAY8RATION",
			85 => "DAY8AFTERNON",
			86 => "DAY8LUNCH",
			87 => "DAY2ZHOR",
			88 => "DAY2SECONDBREAKFAST",
			89 => "DAY2BREAKFAST",
			90 => "DAY2DINNER",
			91 => "DAY2RATION",
			92 => "DAY2AFTERNON",
			93 => "DAY2LUNCH",
			94 => "DAY9ZHOR",
			95 => "DAY9SECONDBREAKFAST",
			96 => "DAY9BREAKFAST",
			97 => "DAY9DINNER",
			98 => "DAY9RATION",
			99 => "DAY9AFTERNON",
			100 => "DAY9LUNCH",
			101 => "DAY0ZHOR",
			102 => "DAY0SECONDBREAKFAST",
			103 => "DAY0BREAKFAST",
			104 => "DAY0DINNER",
			105 => "DAY0RATION",
			106 => "DAY0AFTERNON",
			107 => "DAY0LUNCH",
			108 => "CALORIES",
			109 => "DAY1NAME",
			110 => "DAY0NAME",
			111 => "DAY2NAME",
			112 => "DAY3NAME",
			113 => "DAY4NAME",
			114 => "DAY5NAME",
			115 => "DAY6NAME",
			116 => "DAY7NAME",
			117 => "DAY8NAME",
			118 => "DAY9NAME",
			119 => "EXPECTEDEFFECT",
			120 => "DAY1ZHOR",
			121 => "DAY1SECONDBREAKFAST",
			122 => "DAY1BREAKFAST",
			123 => "DAY1DINNER",
			124 => "DAY1RATION",
			125 => "DAY1AFTERNON",
			126 => "DAY1LUNCH",
			127 => "PERIOD",
			128 => "DAY5ZHOR",
			129 => "DAY5SECONDBREAKFAST",
			130 => "DAY5BREAKFAST",
			131 => "DAY5DINNER",
			132 => "DAY5RATION",
			133 => "DAY5AFTERNON",
			134 => "DAY5LUNCH",
			135 => "DAY7ZHOR",
			136 => "DAY7SECONDBREAKFAST",
			137 => "DAY7BREAKFAST",
			138 => "DAY7DINNER",
			139 => "DAY7RATION",
			140 => "DAY7AFTERNON",
			141 => "DAY7LUNCH",
			142 => "TYPEOFFOOD",
			143 => "DAY3ZHOR",
			144 => "DAY3SECONDBREAKFAST",
			145 => "DAY3BREAKFAST",
			146 => "DAY3DINNER",
			147 => "DAY3RATION",
			148 => "DAY3AFTERNON",
			149 => "DAY3LUNCH",
			150 => "ACTIVITYLEVEL",
			151 => "DAY4ZHOR",
			152 => "DAY4SECONDBREAKFAST",
			153 => "DAY4BREAKFAST",
			154 => "DAY4DINNER",
			155 => "DAY4RATION",
			156 => "DAY4AFTERNON",
			157 => "DAY4LUNCH",
			158 => "DAY6ZHOR",
			159 => "DAY6SECONDBREAKFAST",
			160 => "DAY6BREAKFAST",
			161 => "DAY6DINNER",
			162 => "DAY6RATION",
			163 => "DAY6AFTERNON",
			164 => "DAY6LUNCH",
			165 => "",
		),

		"DETAIL_SET_CANONICAL_URL" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"FILE_404" => "",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_NAME" => "arrFilter",
		"FILTER_PROPERTY_CODE" => array(
			0 => "",
			1 => "EXPECTEDEFFECT",
			2 => "PERIOD",
			3 => "TYPEOFFOOD",
			4 => "ACTIVITYLEVEL",
			5 => "",
		),
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => \Local\Core\Assistant\Iblock\Iblock::getIdByCode("SERVICES","PROGRAMS"),
		"IBLOCK_TYPE" => "SERVICES",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"LIST_ACTIVE_DATE_FORMAT" => "d.m.Y",
		"LIST_FIELD_CODE" => array(
			0 => "SHOW_COUNTER",
			1 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "",
			1 => "CALORIES",
			2 => "",
		),
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "6",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => "more",
		"PAGER_TITLE" => "Новости",
		"PREVIEW_TRUNCATE_LEN" => "",
		"SEF_FOLDER" => "/programs/list/",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "Y",
		"SHOW_404" => "Y",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "Y",
		"USE_PERMISSIONS" => "N",
		"USE_RATING" => "N",
		"USE_REVIEW" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "N",
		"COMPONENT_TEMPLATE" => "programs",
		"SEF_URL_TEMPLATES" => array(
			"news" => "/programs/list/",
			"section" => "",
			"detail" => "#ELEMENT_CODE#/",
		)
	),
	false
);?>
	</div>
</section>


<? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>
